### PR TITLE
Performing a check to make sure that the segmentation map from the ch…

### PR DESCRIPTION
**Pull request by siavashk**
…ild class is actually boolean array before performing bitwise logical not

Re #264

### CODE REVIEW

**Comment by jakeret** [comment]
thanks a lot for contributing to the code base (and sorry for leaving the PR open for so long)

**Comment by siavashk** [comment]
It's OK. Since the last time that we communicated, I have implemented the following quality-of-lif enhancements to your code base:

1. Support for `SAME` padding so that the input image and output segmentation match in width and height.
2. Script for loading the trained model directly from the checkpoint as opposed to creating a U-Net model first and then loading weights from the model directory.

I can make these changes in my fork and do a pull request if you have bandwidth to review them.

**Comment by jakeret** [comment]
@siavashk  I just realized that I never replied you - I'm very sorry for that.

I would be very interested in those two extensions - hope your still willing to contribute to this project

**Comment by siavashk** [comment]
Unfortunately, I left my position and I no longer have access to my fork. But thanks for putting this code out there!

**Pull request merged**
